// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extract_numbers_from_records_cpp
NumericMatrix extract_numbers_from_records_cpp(CharacterVector records, int expected_numbers_per_record);
RcppExport SEXP _sapfluxr_extract_numbers_from_records_cpp(SEXP recordsSEXP, SEXP expected_numbers_per_recordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type records(recordsSEXP);
    Rcpp::traits::input_parameter< int >::type expected_numbers_per_record(expected_numbers_per_recordSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_numbers_from_records_cpp(records, expected_numbers_per_record));
    return rcpp_result_gen;
END_RCPP
}
// parse_ict_records_cpp
List parse_ict_records_cpp(CharacterVector records, NumericVector pulse_times, int measurement_interval, int expected_diagnostics);
RcppExport SEXP _sapfluxr_parse_ict_records_cpp(SEXP recordsSEXP, SEXP pulse_timesSEXP, SEXP measurement_intervalSEXP, SEXP expected_diagnosticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type records(recordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pulse_times(pulse_timesSEXP);
    Rcpp::traits::input_parameter< int >::type measurement_interval(measurement_intervalSEXP);
    Rcpp::traits::input_parameter< int >::type expected_diagnostics(expected_diagnosticsSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_ict_records_cpp(records, pulse_times, measurement_interval, expected_diagnostics));
    return rcpp_result_gen;
END_RCPP
}
// extract_datetimes_cpp
CharacterVector extract_datetimes_cpp(CharacterVector records);
RcppExport SEXP _sapfluxr_extract_datetimes_cpp(SEXP recordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type records(recordsSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_datetimes_cpp(records));
    return rcpp_result_gen;
END_RCPP
}
// calc_hrm_cpp
List calc_hrm_cpp(NumericVector dTratio_douo, NumericVector dTratio_diui, LogicalVector HRM_period, NumericVector tp, double diffusivity, double probe_spacing);
RcppExport SEXP _sapfluxr_calc_hrm_cpp(SEXP dTratio_douoSEXP, SEXP dTratio_diuiSEXP, SEXP HRM_periodSEXP, SEXP tpSEXP, SEXP diffusivitySEXP, SEXP probe_spacingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dTratio_douo(dTratio_douoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dTratio_diui(dTratio_diuiSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type HRM_period(HRM_periodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type diffusivity(diffusivitySEXP);
    Rcpp::traits::input_parameter< double >::type probe_spacing(probe_spacingSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_hrm_cpp(dTratio_douo, dTratio_diui, HRM_period, tp, diffusivity, probe_spacing));
    return rcpp_result_gen;
END_RCPP
}
// calc_mhr_cpp
List calc_mhr_cpp(NumericVector deltaT_do, NumericVector deltaT_di, NumericVector deltaT_uo, NumericVector deltaT_ui, double diffusivity, double probe_spacing, int pre_pulse);
RcppExport SEXP _sapfluxr_calc_mhr_cpp(SEXP deltaT_doSEXP, SEXP deltaT_diSEXP, SEXP deltaT_uoSEXP, SEXP deltaT_uiSEXP, SEXP diffusivitySEXP, SEXP probe_spacingSEXP, SEXP pre_pulseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_do(deltaT_doSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_di(deltaT_diSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_uo(deltaT_uoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_ui(deltaT_uiSEXP);
    Rcpp::traits::input_parameter< double >::type diffusivity(diffusivitySEXP);
    Rcpp::traits::input_parameter< double >::type probe_spacing(probe_spacingSEXP);
    Rcpp::traits::input_parameter< int >::type pre_pulse(pre_pulseSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_mhr_cpp(deltaT_do, deltaT_di, deltaT_uo, deltaT_ui, diffusivity, probe_spacing, pre_pulse));
    return rcpp_result_gen;
END_RCPP
}
// preprocess_pulse_data_cpp
List preprocess_pulse_data_cpp(NumericVector do_vec, NumericVector di_vec, NumericVector uo_vec, NumericVector ui_vec, int pre_pulse);
RcppExport SEXP _sapfluxr_preprocess_pulse_data_cpp(SEXP do_vecSEXP, SEXP di_vecSEXP, SEXP uo_vecSEXP, SEXP ui_vecSEXP, SEXP pre_pulseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type do_vec(do_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type di_vec(di_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type uo_vec(uo_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ui_vec(ui_vecSEXP);
    Rcpp::traits::input_parameter< int >::type pre_pulse(pre_pulseSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocess_pulse_data_cpp(do_vec, di_vec, uo_vec, ui_vec, pre_pulse));
    return rcpp_result_gen;
END_RCPP
}
// calc_tmax_coh_cpp
List calc_tmax_coh_cpp(NumericVector deltaT_do, NumericVector deltaT_di, double diffusivity, double probe_spacing, int pre_pulse);
RcppExport SEXP _sapfluxr_calc_tmax_coh_cpp(SEXP deltaT_doSEXP, SEXP deltaT_diSEXP, SEXP diffusivitySEXP, SEXP probe_spacingSEXP, SEXP pre_pulseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_do(deltaT_doSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_di(deltaT_diSEXP);
    Rcpp::traits::input_parameter< double >::type diffusivity(diffusivitySEXP);
    Rcpp::traits::input_parameter< double >::type probe_spacing(probe_spacingSEXP);
    Rcpp::traits::input_parameter< int >::type pre_pulse(pre_pulseSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_tmax_coh_cpp(deltaT_do, deltaT_di, diffusivity, probe_spacing, pre_pulse));
    return rcpp_result_gen;
END_RCPP
}
// calc_tmax_klu_cpp
List calc_tmax_klu_cpp(NumericVector deltaT_do, NumericVector deltaT_di, double diffusivity, double probe_spacing, double tp_1, int pre_pulse);
RcppExport SEXP _sapfluxr_calc_tmax_klu_cpp(SEXP deltaT_doSEXP, SEXP deltaT_diSEXP, SEXP diffusivitySEXP, SEXP probe_spacingSEXP, SEXP tp_1SEXP, SEXP pre_pulseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_do(deltaT_doSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_di(deltaT_diSEXP);
    Rcpp::traits::input_parameter< double >::type diffusivity(diffusivitySEXP);
    Rcpp::traits::input_parameter< double >::type probe_spacing(probe_spacingSEXP);
    Rcpp::traits::input_parameter< double >::type tp_1(tp_1SEXP);
    Rcpp::traits::input_parameter< int >::type pre_pulse(pre_pulseSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_tmax_klu_cpp(deltaT_do, deltaT_di, diffusivity, probe_spacing, tp_1, pre_pulse));
    return rcpp_result_gen;
END_RCPP
}
// calc_hrmx_cpp
List calc_hrmx_cpp(NumericVector deltaT_do, NumericVector deltaT_di, NumericVector deltaT_uo, NumericVector deltaT_ui, NumericVector dTratio_douo, NumericVector dTratio_diui, NumericVector tp, double L, double H, double diffusivity, double probe_spacing, int idx_do_max, int idx_di_max, int idx_uo_max, int idx_ui_max, double dTdo_max, double dTdi_max, double dTuo_max, double dTui_max);
RcppExport SEXP _sapfluxr_calc_hrmx_cpp(SEXP deltaT_doSEXP, SEXP deltaT_diSEXP, SEXP deltaT_uoSEXP, SEXP deltaT_uiSEXP, SEXP dTratio_douoSEXP, SEXP dTratio_diuiSEXP, SEXP tpSEXP, SEXP LSEXP, SEXP HSEXP, SEXP diffusivitySEXP, SEXP probe_spacingSEXP, SEXP idx_do_maxSEXP, SEXP idx_di_maxSEXP, SEXP idx_uo_maxSEXP, SEXP idx_ui_maxSEXP, SEXP dTdo_maxSEXP, SEXP dTdi_maxSEXP, SEXP dTuo_maxSEXP, SEXP dTui_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_do(deltaT_doSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_di(deltaT_diSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_uo(deltaT_uoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type deltaT_ui(deltaT_uiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dTratio_douo(dTratio_douoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dTratio_diui(dTratio_diuiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type diffusivity(diffusivitySEXP);
    Rcpp::traits::input_parameter< double >::type probe_spacing(probe_spacingSEXP);
    Rcpp::traits::input_parameter< int >::type idx_do_max(idx_do_maxSEXP);
    Rcpp::traits::input_parameter< int >::type idx_di_max(idx_di_maxSEXP);
    Rcpp::traits::input_parameter< int >::type idx_uo_max(idx_uo_maxSEXP);
    Rcpp::traits::input_parameter< int >::type idx_ui_max(idx_ui_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dTdo_max(dTdo_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dTdi_max(dTdi_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dTuo_max(dTuo_maxSEXP);
    Rcpp::traits::input_parameter< double >::type dTui_max(dTui_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_hrmx_cpp(deltaT_do, deltaT_di, deltaT_uo, deltaT_ui, dTratio_douo, dTratio_diui, tp, L, H, diffusivity, probe_spacing, idx_do_max, idx_di_max, idx_uo_max, idx_ui_max, dTdo_max, dTdi_max, dTuo_max, dTui_max));
    return rcpp_result_gen;
END_RCPP
}
// detect_outliers_rolling_mean_cpp
IntegerVector detect_outliers_rolling_mean_cpp(NumericVector vh_values, int window, double threshold);
RcppExport SEXP _sapfluxr_detect_outliers_rolling_mean_cpp(SEXP vh_valuesSEXP, SEXP windowSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_outliers_rolling_mean_cpp(vh_values, window, threshold));
    return rcpp_result_gen;
END_RCPP
}
// detect_rate_of_change_outliers_cpp
IntegerVector detect_rate_of_change_outliers_cpp(NumericVector vh_values, double max_change);
RcppExport SEXP _sapfluxr_detect_rate_of_change_outliers_cpp(SEXP vh_valuesSEXP, SEXP max_changeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type max_change(max_changeSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_rate_of_change_outliers_cpp(vh_values, max_change));
    return rcpp_result_gen;
END_RCPP
}
// identify_gaps_cpp
List identify_gaps_cpp(NumericVector datetimes, NumericVector vh_values, LogicalVector is_na);
RcppExport SEXP _sapfluxr_identify_gaps_cpp(SEXP datetimesSEXP, SEXP vh_valuesSEXP, SEXP is_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type datetimes(datetimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_na(is_naSEXP);
    rcpp_result_gen = Rcpp::wrap(identify_gaps_cpp(datetimes, vh_values, is_na));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_linear_cpp
NumericVector interpolate_linear_cpp(NumericVector vh_values, NumericVector datetimes, int gap_start, int gap_end);
RcppExport SEXP _sapfluxr_interpolate_linear_cpp(SEXP vh_valuesSEXP, SEXP datetimesSEXP, SEXP gap_startSEXP, SEXP gap_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type datetimes(datetimesSEXP);
    Rcpp::traits::input_parameter< int >::type gap_start(gap_startSEXP);
    Rcpp::traits::input_parameter< int >::type gap_end(gap_endSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_linear_cpp(vh_values, datetimes, gap_start, gap_end));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_weighted_cpp
NumericVector interpolate_weighted_cpp(NumericVector vh_values, NumericVector datetimes, int gap_start, int gap_end, int window_size);
RcppExport SEXP _sapfluxr_interpolate_weighted_cpp(SEXP vh_valuesSEXP, SEXP datetimesSEXP, SEXP gap_startSEXP, SEXP gap_endSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type datetimes(datetimesSEXP);
    Rcpp::traits::input_parameter< int >::type gap_start(gap_startSEXP);
    Rcpp::traits::input_parameter< int >::type gap_end(gap_endSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_weighted_cpp(vh_values, datetimes, gap_start, gap_end, window_size));
    return rcpp_result_gen;
END_RCPP
}
// interpolate_all_gaps_cpp
List interpolate_all_gaps_cpp(NumericVector vh_values, NumericVector datetimes, IntegerVector gap_starts, IntegerVector gap_ends, NumericVector gap_durations, double max_gap_hours, std::string method, int window_size);
RcppExport SEXP _sapfluxr_interpolate_all_gaps_cpp(SEXP vh_valuesSEXP, SEXP datetimesSEXP, SEXP gap_startsSEXP, SEXP gap_endsSEXP, SEXP gap_durationsSEXP, SEXP max_gap_hoursSEXP, SEXP methodSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vh_values(vh_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type datetimes(datetimesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gap_starts(gap_startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gap_ends(gap_endsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gap_durations(gap_durationsSEXP);
    Rcpp::traits::input_parameter< double >::type max_gap_hours(max_gap_hoursSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(interpolate_all_gaps_cpp(vh_values, datetimes, gap_starts, gap_ends, gap_durations, max_gap_hours, method, window_size));
    return rcpp_result_gen;
END_RCPP
}
// prefilter_flagged_rows_cpp
List prefilter_flagged_rows_cpp(CharacterVector quality_flags, CharacterVector flags_to_interpolate, Nullable<CharacterVector> method_col, Nullable<CharacterVector> sensor_col);
RcppExport SEXP _sapfluxr_prefilter_flagged_rows_cpp(SEXP quality_flagsSEXP, SEXP flags_to_interpolateSEXP, SEXP method_colSEXP, SEXP sensor_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type quality_flags(quality_flagsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type flags_to_interpolate(flags_to_interpolateSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type method_col(method_colSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type sensor_col(sensor_colSEXP);
    rcpp_result_gen = Rcpp::wrap(prefilter_flagged_rows_cpp(quality_flags, flags_to_interpolate, method_col, sensor_col));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sapfluxr_extract_numbers_from_records_cpp", (DL_FUNC) &_sapfluxr_extract_numbers_from_records_cpp, 2},
    {"_sapfluxr_parse_ict_records_cpp", (DL_FUNC) &_sapfluxr_parse_ict_records_cpp, 4},
    {"_sapfluxr_extract_datetimes_cpp", (DL_FUNC) &_sapfluxr_extract_datetimes_cpp, 1},
    {"_sapfluxr_calc_hrm_cpp", (DL_FUNC) &_sapfluxr_calc_hrm_cpp, 6},
    {"_sapfluxr_calc_mhr_cpp", (DL_FUNC) &_sapfluxr_calc_mhr_cpp, 7},
    {"_sapfluxr_preprocess_pulse_data_cpp", (DL_FUNC) &_sapfluxr_preprocess_pulse_data_cpp, 5},
    {"_sapfluxr_calc_tmax_coh_cpp", (DL_FUNC) &_sapfluxr_calc_tmax_coh_cpp, 5},
    {"_sapfluxr_calc_tmax_klu_cpp", (DL_FUNC) &_sapfluxr_calc_tmax_klu_cpp, 6},
    {"_sapfluxr_calc_hrmx_cpp", (DL_FUNC) &_sapfluxr_calc_hrmx_cpp, 19},
    {"_sapfluxr_detect_outliers_rolling_mean_cpp", (DL_FUNC) &_sapfluxr_detect_outliers_rolling_mean_cpp, 3},
    {"_sapfluxr_detect_rate_of_change_outliers_cpp", (DL_FUNC) &_sapfluxr_detect_rate_of_change_outliers_cpp, 2},
    {"_sapfluxr_identify_gaps_cpp", (DL_FUNC) &_sapfluxr_identify_gaps_cpp, 3},
    {"_sapfluxr_interpolate_linear_cpp", (DL_FUNC) &_sapfluxr_interpolate_linear_cpp, 4},
    {"_sapfluxr_interpolate_weighted_cpp", (DL_FUNC) &_sapfluxr_interpolate_weighted_cpp, 5},
    {"_sapfluxr_interpolate_all_gaps_cpp", (DL_FUNC) &_sapfluxr_interpolate_all_gaps_cpp, 8},
    {"_sapfluxr_prefilter_flagged_rows_cpp", (DL_FUNC) &_sapfluxr_prefilter_flagged_rows_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_sapfluxr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
